### PR TITLE
#1448 - Add search bar on help board with a search button

### LINKED ISSUE #1448: [Desktop][Mobile] Add search bar on help board with a search button
## Feature Summary

Please read [this comment down below](https://github.com/FightPandemics/FightPandemics/issues/1448#issuecomment-691365032).

## Value

Search keyword feature will make the search capability of Fight Pandemics very effective for the users. This in turn will greatly improve user experience and help users quickly find relevant help.

## End Goal

User lands on the post, organization profile, individual profile he/she is looking for.

### LINKED ISSUE #1613: Search for Help Board on Web Test Documentation related to #1448
**Note**: This is how the FP system work for the Help Board Search. Update the note basing on logged defects and f_searchkeyword chanel (Slack) . Defect’s information is attached on the excel sheet along.

1-	Click on Help Board link/View Help Board link to navigate to Help Board Feed page.
2-	Validate the Search Bar in between Fight Pandemics logo and About Us  (for Web).
3-	Validation the Search Bar under Help Board (for Mobile).
4-	Validate Default Health Board Feed page has NO 3 TABS – POSTS – Organizations and People and All Posts on the left is highlighted (Web testing)
5-	Validate the Search bar has Search Posts, People & Orgs in the grey text.
6-	Validation the search bar will appear with the following drop-down options to save spaces (mobile/small screens)
image

 
7-	Search Icon on the search bar is enabled and clickable.
8-	Close X icon on the search bar is visible and clickable if there is keyword(s) on the search bar.
9-	Click on X icon will empty the search bar keyword and refresh the search result, back to the default page without 3 tabs(Web).  If there is existing filters like Location, Provider, Types, Requesting Help/Offering Help,  these filters still keep intact and applied to the current display.  There is no highlight on search result.
10-	Click on Search Icon and if keyword is <2 characters - Validation message is on display in red "Min. 2 characters"
11-	Enter keywords and click on Search Icon or Enter, see the 3 TABS POSTS – Organizations and People (Web Testing).
12-	Verify the validation message for Posts tab if there is no record in return
Sorry, there are currently no relevant posts available. Please try using a different filter search or [create a post](url).   
13-	When clicking on [create a post](url), an unsigned user will be directed to the page  /auth/login.
14-	Enter keywords to search for Post, 
**Unsigned User** –  Post Individual/Organization records will return if there is at least one 100% match for whole word in Title and/or Description and/or Name and/or Content.  Keywords will be highlighted on each post on search result. Click on Filters, Posts can be filter by  (after providing all the filters values, need to click on Apply Filter button to see the filter result).
- Location – Partial match will be included on the search since the location is known and Post visibility must be taken in account for the search. 
- Provider
- Type

**Signed User** - Post Individual/Organization records will return if there is partial match for keywords in Title and/or Description and/or Name and/or Content.  If Individual/Organization Posts having visibility restriction on city/state/country is not on the same as Individual’s profile, these Posts will be hidden from the search result.  Click on Filters, Posts can be filter by Location, Provider and Type. 

15- Sort for Posts (no Signed) will be based on Weight Title: 5; Content: 3; Type (tags): 2; Author Name: 1 (keywords/other-text ratio) with highest scores are on the top.
16-	Sort for Posts (with Signed) will be based on the location of individual profile. The Closest location is on the top. The Posts of signed user are also in display if matching the keywords.
17-	In order to Likes or Comments on the any Post, the user needs to log in.
18-	Post result will ALWAYS return records even there is nothing match with new location when applying the new location filter on the subset of at least one Post record
19-	Posts if searching by location, it will be based on the visibility of the POST (city, state, country, word-wide) and duration (a day, week, month, forever).  For duration, at this time, we can test within a day due to have no-time shifting environment (or we can modify in the back end of the POST).  For this document, I just focus on visibility scope.   If Post 's visibility within city, search and match keywords=>POST display =>Filter with same city =>POST display =>Filter with different city =>POST Don't display.   The same logic applies for (state, country).  For word-wide visibility, the POST is ALWAY display if match the keyword.
20-	Results of Posts if  filtering by new location, the Posts matching with new locations will be put on the top.
21-	Using the same keywords , user can get the results for POSTS , Organizations and People without the need to re-type.  The result will display correspond with focus TAB (Web) or  Posts/Organizations/People Search Type (Mobile).
22-  If keywords are two/three-letters words , the search result will be matched and highlighted if there is full-match (ex: **do** or **did** keywords will only matched and highlighted  full-words **do** or **did**).  If keywords have from four-letters words up,  The partial search is performed by comparing the letters from **the start of the word** (ex: **here** keyword should NOT be displayed/matched with **there** word, but **star** keyword will be displayed/highlighted in **star**ting/**star**k/**star**ving).   The partial match is only for signed user search or unsigned user plus filter location search.   This rule applies for Posts, Organization and People Search 
23-  For NON English - also apply for all types of search.
If a non English letter was used, all those rules will change, there will be one rule:
a. Words with 2 or more characters will partially match while English requires at least four-letters word to be partially match.
b. search and match can be performed **within the word** too i.e. match will not be performed ONLY from start as English or end of the word. It can locate the word **anywhere** in the text for international languages.
24-	Enter keywords to search for Organization, 
**Unsigned User** –  Organization records will return if there is at least one 100% match for whole word in Name and/or About.  Keywords will be highlighted on each Organization record on search result. Click on Filters, Organizations can be filter by Location Only   (after providing the filter values, need to click on Apply Filter button to see the filter result).  Partial match will be included on the search since the location is known.
**Signed User** - Organization records will return if there is partial match for keywords in Name and/or About.  
25-  In order to Send Message to any Organization from the Organization search result, the user needs to sign in.
26- Result Organizations can be filtered by location only when Organizations tab is on focus(Web) or Organizations Search Type (Mobile).  Organizations result will ALWAYS return records even there is nothing match with new location when applying the new location filter on the subset of at least one Organizations record.
27- Sort for Organizations (no Signed) will be based on Weight Name:2; About: 1 (keywords/other-text ratio) with highest scores are on the top.
28- Sort for Organizations (with Signed) will be based on the location of Organization profile. The Closest location is on the top. The Organizations of signed user are also in display if matching the keywords.
29-	Enter keywords to search for People, 
**Unsigned User** –  People records will return if there is at least one 100% match for whole word in Name and/or About.  Keywords will be highlighted on each People record on search result. Click on Filters, People can be filter by Location Only   (after providing the filter values, need to click on Apply Filter button to see the filter result).  Partial match will be included on the search since the location is known.
**Signed User** - People records will return if there is partial match for keywords in Name and/or About.  
30- Sort for People (no Signed) will be based on Weight Name:2; About: 1 (keywords/other-text ratio) with highest scores are on the top.
31-Sort for People (with Signed) will be based on the location of individual profile. The Closest location is on the top. The Individual of signed user are also in display if matching the keywords.
32- Result People can be filtered by location only when People tab is on focus (web) or People Search Type (Mobile)
33- People result will ALWAYS return records even there is nothing match with new location when applying the new location filter on the subset of at least one People record. (edited) .
34- In order to Check on Media type: Facebook, Install Gram, Linked , Twister …etc. to any People  record from the People search result, the user needs to sign in.
35- Individual can select show/not show the address to be included/hidden from the location filter. When choosing not show the address, the people record will not in the result of search keyword on people with location filter.
36-**Apply filters**- After selecting the filter value for Location and/or Provider and/or Type (Web and Mobile) , Requesting Help or Offering Help (Mobile), we need to click on Apply Filter to apply the selected filters value on the result.
image

37-**Clear filters**-Click on Clear Filter option only clear Location , Provider and Type values.  It doesn't clear the Requesting Help or Offering Help (Web /Mobile) and All Posts (Web).
image

38- Refresh on Help Board Feed page will provide after solved  #1640.   Need to check on how refresh works on two different flows: a) via Help Board/View Help Board link  b) via need-help#Step2 or offer-help#Step2

### LINKED ISSUE #1684: Post Search results are not matching the search criteria.
1. Open STG, and navigate to Help Board.
2. Enter search text 'HelpNextDoor.net' and hit <enter>to search

You will observe that 7 records are displayed. But only 2 post have actual searched text. All other post have no matching text. Refer below GIF.

image

**More test data** :
- Wrong text is matched with the search text, I search for 'The novel' but it also search the words as 'further', 'Other', refer below screenshot
- Also while searching multiple words, search is performed as each single word like in the screenshots
search-of

serach-multiple-words

wrong-search

### LINKED ISSUE #1686: Mobile: Search functionality is not user friendly
1. Open the STG url on mobile, and navigate to the help Board
2. Enter the search text in the search textbox.

Issue: You will observe that nothing will happen, nor any user message is displayed to select the 'TABs' to perform the search.
Here either it should work as like in desktop, by entering the text and selecting the TAB or user need to be notified to select the TAB before entering the search text.

Refer below GIF.
ezgif com-gif-maker (22)

### LINKED ISSUE #1691: Search functionality for International languages is not working as expected and we should NOT limit the letters in a word to search
1. Login into STG and navigate to Help Board
2. Change language to German and search for text , help i.e. 'Hilfe' in German language 

Issue: You will observe that search is performed differently when the text is entered as single word or if it is entered as part of multiple words. refer below screenshot.

search-german-1

**Expected Result: We should remove the condition on the number of the letters in a word to perform search**

While searching for Chinese post, the search is not performed word wise, please see the screenshot below:

search-chinese

Also as per @ddveloper for chinese search:
It's actually not that frequent to search one character in Chinese, the most common I would say is 2 characters plus.
https://docs.acquia.com/acquia-search/language/non-latin/ for reference

### LINKED ISSUE #1701: HB Feed search result should retain the highlight searched keyword when navigating back from the post page
1-Navigate to Help Board Feed page and enter keyword , click on search icon
2-See the result of posts that contains at least one keyword
3-Click on the post that has [view more](url) link since the post is too long and the keyword might be hidden.
4-The post page for the Post is on display.
5-**Right here,  It is nice to see the keyword is highlight on this post.**
6-After viewing the post , click on  [<- Back](url) to go back the previous search result.
7- **Expect to see search result still retains the highlight keywords, so the user can continue to review the rest of the posts.** 
Otherwise, they might need to perform the same search to see the highlight keyword match

please see the GIF.
Result_keyword_hightligh

### LINKED ISSUE #1702: HB-Search keyword on people should get all the individual records having keywords matching name and/or about
1-User enters keyword to search : for example - the 
2-Click on People tab and get two records with the on about each record
3-Click on Filter and enter -San Jose , CA for location and click on Apply Filters
4-**Since the Individual 's first record checked on Don't show my address on profile , the first record is not in display as expected and the second record is on the top since Individual has San Jose , CA address**
5- Also see 4 more records have 'the' in the Name.  **Expect- These 4 news records should display on step 2.  Step 2 should have 6 records instead of 2 records** 
6- **if click x to remove the location , we come back on 2 records we have on step 2 which I expect to see 6 records.**
please see the GIF 

People_search

### LINKED ISSUE #1714: Health board search- Icon search has no response when clicking on it
SC1
1-navigate to feed page
2-enter keywords and click on search icon 
**3-see no response ,  so we need to press on enter key**
searchIconNotResponseSC1

SC2
1-navigate to feed page and enter one character keyword
2-see validation message -min. 2 characters
3-enter 3 characters keywords and click on search icon
4- **see no response** , press enter key and see the result
5- click on X icon to clear the search
6- enter new keywords 3 characters 
**7-click on Search icon , and see no response**

searchIconNotResponse

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
Add search bar on help board with a search button

_Please be concise and link any related issue(s):_
closes #1701
closes #1702
closes #1691
closes #1686
closes #1684

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@Zaydme 
- Issue #1685 : Search text box is NOT aligned yet, Please see below screenshot :FAIL

image

- Offering/request Help caption is updated, refer below screenshot: PASS

image

- Issue#1686: Mobile Search:
The functionality is changed as when user start typing in the search box, by default the search is performed  for 'POST', But
user cannot switch between the TABs for the same searched keyword. To perform search for the same entered keyword, user need to switch the TAB and the RE-type the word. User should be able to switch between TABs without re-typing the same keyword as in desktop. Refer below GIF: FAIL

ezgif com-gif-maker (26)

**Comment by rabbi08** [comment]
@Zaydme @doheekim93 @joshmorel 
We might need to consider translation for 'Post/Organization/People' in search functionality because 
1. we have these words translated in profiles and 'Create Post' terms.

Currently they are not translated when language is switched.  refer below screenshot.
image


2.  I would like to mention here that this issue is not related to feature, this error message is not translated for the filters as well.
The error messages are also not translated when there is no search data.
Refer below screenshot. 

image

**Comment by Zaydme** [comment]
@rabbi08 you can find all the new keys that need to be translated [here](https://github.com/FightPandemics/FightPandemics/pull/1695/files#diff-99bf3c2a4747cf742692f6639038bd00b15679799bc1ff3580139c34f0dedff1)

note:
One or two keys were originally translated but will need to be translated again (like "All posts"). because some key names had to be changed for differentiation. as an example: 
```diff
-    "all": "All posts",
+    "allPosts": "All posts",
+    "allPeople": "All people",
+    "allOrgs": "All organizations",
```

**Comment by Zaydme** [comment]
@Ritika92 @rabbi08 @doheekim93 current tracked GTM ids are as follow.



And for tracking search keywords that are typed in the input field, a custom "SERACH_KEYWORD" event will be fired 
image
that will contain the search keywords
```js
{
  gtm: {
    ...
  },
  event: 'SEARCH_KEYWORD',
  userId: 'xxxxxxxxxxxxxxxxxxxxxx',
  keyword: 'face mask and sanitizer'
}
```
can you please inform BI team of this to see if it's enough for them, or if they need to track something else.

**Comment by rabbi08** [comment]
@Zaydme 
- The user profile logo/avatar should also be clickable under 'Organization and People' TAB. This is working as expected under 'POST' tab. Refer below GIF.

ezgif com-gif-maker (31)

**Comment by rabbi08** [comment]
@Zaydme 
1. On Mobile, the search results are not updated when user switch between the TABs. unless user click on 'return' specifically. Please see below GIF.
ezgif com-gif-maker (33)

2. Also, can we change the 'return' to 'Search' when user click in 'Search' box? also,  search is performed after clicking on 'magnifier' icon in search box.

3. The user filters are removed, when user perform search.

**Comment by rabbi08** [comment]
> @rabbi08 you can find all the new keys that need to be translated [here](https://github.com/FightPandemics/FightPandemics/pull/1695/files#diff-99bf3c2a4747cf742692f6639038bd00b15679799bc1ff3580139c34f0dedff1)
> 
> note:
> One or two keys were originally translated but will need to be translated again (like "All posts"). because some key names had to be changed for differentiation. as an example:
> 
> ```diff
> -    "all": "All posts",
> +    "allPosts": "All posts",
> +    "allPeople": "All people",
> +    "allOrgs": "All organizations",
> ```

@Zaydme @Ritika92 @doheekim93 
We have to message to #transalation as mentioned by Do Hee in the diagram below. We have to ensure our error messages are translated.

image

**Comment by vandanafs** [comment]
On this feature URL  https://feature1448-help-board-search-bar.fightpandemics.xyz/feed
1.A21 is organization profile created 3 different post as Entertainment as tag and Grocery/Food as tag.
2.Only Grocery/Food tagged post is getting displayed when I search post with  "A21" keyword 
3.It is not displaying the "Entertainment" tags in the results.
please have a look at the attached gif.
ezgif com-gif-maker

**Comment by vandanafs** [comment]
1.When user sets filter and  click on apply filters it will display the results.
2.Upon clicking on any search results and navigating back to browser backward button, set filtered values are clearing automatically.
image

**Comment by Zaydme** [comment]
@vandanafs 
- for [this case](https://github.com/FightPandemics/FightPandemics/pull/1695#issuecomment-716958785) A21 has 2 posts with city visibility, so they are only visible for people in Exton, US. You can try and set a location filter to "Exton, PA, USA" and you will be able to see all 3 posts (as in the image)
image
- for [this issue](https://github.com/FightPandemics/FightPandemics/pull/1695#issuecomment-716967384) there is a work in progress, and that's another feature, plese check https://github.com/FightPandemics/FightPandemics/pull/1709

File: backend/lib/endpoints/organisations.js [hunk 1]
```diff
@@ -16,6 +17,206 @@ async function routes(app) {
...
+        } else if (user === null) {
+          req.log.error(userErr, "User does not exist");
+          throw app.httpErrors.forbidden();
+        }
+      }
+
+      /* eslint-disable sort-keys */
+      const filters = [{ type: { $ne: "Individual" } }];
+
+      // un-comment if user shouldnt find their owned organizations
```
Comment (joshmorel) [inline backend/lib/endpoints/organisations.js]: Do we need this comment? I think it will just be confusing for someone else reading the code later.

File: backend/lib/endpoints/users.js [hunk 2]
```diff
@@ -16,6 +17,205 @@ async function routes(app) {
...
+            { "objectives.shareInformation": true },
+            { "objectives.volunteer": true },
+          ],
+        },
+      };
+
+      if (objective) filters.push(objectives[objective]);
+
+      // if location is defined, use simple regex text query, in order to use $geoNear
+      if (location && keywords) {
```
Comment (idjevm) [inline backend/lib/endpoints/users.js:82]: I think we can convert this regex to a util. I saw it very similarly in 3 different places in the backend.

**Review by idjevm — CHANGES_REQUESTED** [review]
I did also see the same regex in the frontend... I know these can be expensive operations sometimes. 

But yeah, we should be able to reuse them...

File: backend/lib/endpoints/users.js (hunk 2 above)
Comment (idjevm) [reply backend/lib/endpoints/users.js:82]: and at least once in the FE.

Comment (joshmorel) [reply backend/lib/endpoints/users.js:82]: Agreed @idjevm for the backend, they look the same so let's make them a function in `backend/lib/utils.js`.

I see the similar front end functions as well. We can move to util on frontend side too. The `Highlight` fn in:

client/src/components/Feed/Post.js
client/src/components/Feed/User.js

Still haven't gotten around to sharing constants/functions across backend & frontend so let's leave them separate for now.

Comment (Zaydme) [reply backend/lib/endpoints/users.js:82]: moved both on BE and FE to `backend/lib/utils.js` and `components/Feed/utils.js`

File: client/src/pages/Feed.js [hunk 3]
```diff
@@ -466,15 +564,44 @@ const Feed = (props) => {
...
+    let endpoint = `${baseURL}${objectiveURL()}${filterURL()}${searchURL()}`;
     postsDispatch({ type: FETCH_POSTS });
+
     try {
       const {
         data: { data: posts, meta },
       } = await axios.get(endpoint);
+      if (searchKeyword) {
+        // trigger custom GTM event
+        window.dataLayer.push({
```
Comment (joshmorel) [inline client/src/pages/Feed.js]: This breaks for me (did you only get it to work locally for yourself @Zaydme ?).

image


Do you need similar to `client/src/actions/authActions.js` 

```
        // trigger custom GTM event
        TagManager.dataLayer({
          dataLayer: {
            event: "SEARCH_KEYWORD",
            keyword: searchKeyword,
            category: searchCategory || "POSTS",
            resultsCount: meta.total,
          }
        });
```

This no longer breaks for me BUT I don't know if it works the way intended with GTM.

With imports:

```
import TagManager from "react-gtm-module";
```

**Review by joshmorel — CHANGES_REQUESTED** [review]
@Zaydme did you change the position of the search bar?

I can't recall this overlapping issue being the case the last time. 

image

File: client/src/pages/Feed.js (hunk 3 above)
Comment (Zaydme) [reply client/src/pages/Feed.js]: do you have `REACT_APP_GTM_ID`?

**Comment by Zaydme** [comment]
> @Zaydme did you change the position of the search bar?
I can't recall this overlapping issue being the case the last time.

yes, I did center the header search bar lately, I just fixed this overlapping issue :+1:

File: client/src/pages/Feed.js (hunk 3 above)
Comment (Zaydme) [reply client/src/pages/Feed.js]: @joshmorel oh you have QA mode enabled, so GTM is not initialized, I just committed a fix to make sure the dataLayer exists before pushing

Comment (joshmorel) [reply client/src/pages/Feed.js]: > do you have REACT_APP_GTM_ID?
> oh you have QA mode enabled, so GTM is not initialized

@Zaydme QA mode wasn't enabled but like most devs I'm not working with a `GTM_APP_GTM_ID` (both will cause this issue however as GTM is not initialized). 

> I just committed a fix to make sure the dataLayer exists before pushing

This will work but such a check must also be included when using `TagManager.dataLayer` (react library). Is there anything else it might do vs using window.dataLayer directly? @idjevm  Probably not much but we should be sure.

Comment (Zaydme) [reply client/src/pages/Feed.js]: @joshmorel
I think that's what the GTM library does, because I just followed the GTM documentations and what they do is pushing an object to `window.dataLayer` 
I tested with the staging GTM and everything seems to be working.

**Comment by joshmorel** [comment]
@Zaydme  https://github.com/FightPandemics/FightPandemics/blob/b347a0392498cb682c1de4e1d1110903b0020d62/client/src/actions/authActions.js#L22

Uses the function:

https://github.com/alinemorelli/react-gtm/blob/796bd199384de2a7eca36766ba16219fe1bb892b/src/TagManager.js#L45

Which practically works the same as `if (window.dataLayer) window.dataLayer.push...` but with some additions... Probably best to be consistent with using the react-gtm-module like in `authActions`. Otherwise I think we are good from my perspective.

File: client/src/pages/Feed.js [hunk 4]
```diff
@@ -466,15 +564,44 @@ const Feed = (props) => {
...
+    let endpoint = `${baseURL}${objectiveURL()}${filterURL()}${searchURL()}`;
     postsDispatch({ type: FETCH_POSTS });
+
     try {
       const {
         data: { data: posts, meta },
       } = await axios.get(endpoint);
+      if (searchKeyword && window.dataLayer) {
+        // trigger custom GTM event
+        window.dataLayer.push({
```
Comment (joshmorel) [inline client/src/pages/Feed.js]:
```suggestion
        TagManager.dataLayer({
          dataLayer: {
            event: "SEARCH_KEYWORD",
            keyword: searchKeyword,
            category: searchCategory || "POSTS",
            resultsCount: meta.total,
          }
        });

```

A bit nit-picky but can we use the gtm library for consistency?

You just need to also at the top:

```
import TagManager from "react-gtm-module";
```

Other than that I'm good code wise we can merge after deploy. @idjevm

**Review by joshmorel — CHANGES_REQUESTED** [review]

File: client/src/pages/Feed.js (hunk 4 above)
Comment (Zaydme) [reply client/src/pages/Feed.js]: i am changing that, I will commit in few minutes

**Review by joshmorel — APPROVED** [review]
Thanks @Zaydme I'm happy with this. Great work!

After prod deploy and with one more approval we'll merge to staging.

**Review by idjevm — APPROVED** [review]
LGTM ! We can merge it after staging is merged into prod soon.

**Comment by rabbi08** [comment]
@Zaydme 
Search is not working as of now, please see below GIF.
ezgif com-gif-maker (34)

**Comment by Zaydme** [comment]
> @Zaydme 
> Search is not working as of now, please see below GIF.
> ezgif com-gif-maker (34)
> 

@rabbi08 we have changed the db in preparation for the merge, so search functionality won't be working now.

**Comment by vandanafs** [comment]
> > @Zaydme
> > Search is not working as of now, please see below GIF.
> > ezgif com-gif-maker (34)
> 
> @rabbi08 we have changed the db in preparation for the merge, so search functionality won't be working now.

@rabbi08 :How long it is not going to work?

**Comment by Zaydme** [comment]
> @rabbi08 :How long it is not going to work?

@rabbi08 it should work just after the merge to staging
