### PR TITLE
fixing some GTM tags

### LINKED ISSUE #1642: GTM ID need fixes
**Please make sure the id attributes are updated for the mobile version as well!!**

Please assign the following elements with the listed JSX 'id' attributes.

Please also note, when assigning id attribute, to assign it to the area that encompasses the entire button or element (including any _clickable_ WHITE SPACE around text).
Example: not just the text "Next", but the entire button (including Next and arrow symbol)
Screen Shot 2020-07-03 at 6 43 37 PM

### Path: /organisation/##### (where ### indicates org ID number)
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 1. | Email Icon | ORG_EM |

Screen Shot 2020-10-12 at 10 41 32 AM

### Path:  /profile/##### and  /organisation/#####
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 2. | Upload Avatar Icon (Camera) - Individual Profile | PR_UA |
| 3. | Upload Avatar Icon (Camera) - Org Profile | ORG_UA |

Screen Shot 2020-10-12 at 10 43 56 AM

For ID not firing in GTM, please refer to this set of [instructions](https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255) on how to debug GTM tags in your local environment.

### LINKED ISSUE #1643: Localisation: GTM IDs not firing
Please make sure that the ID include all elements in component!

The following IDs have already been assigned to the correct components. Issue is that GTM does not pick up on these IDs.

| Component on page | JSX 'id' attribute |
| --- | --- |
| Chinese Traditional | NAV_LS_ZH_TW |
| English (US) | NAV_LS_EN_US |
| English (UK) | NAV_LS_EN_UK | 
| German | NAV_LS_DE |
| Polish | NAV_LS_PL |
| Spanish (Peninsular) | NAV_LS_ES_ES |

Desktop:
Screen Shot 2020-10-12 at 1 31 59 PM

Mobile:
Screen Shot 2020-10-12 at 1 34 45 PM

### LINKED ISSUE #1644: GTM ID not showing up
**How to set up GTM debugging on Local: [https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255](https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255)

The following IDs have already been assigned to the correct components. Issue is that GTM does **not** pick up on these IDs.

### 1. Onboarding Flow

**Issue:** `Enter address, zip code, or city` ID does not show up on GTM when clicked on.

| Component on page | JSX 'id' attribute | url path |
| --- | --- | ---|
| "Enter address, zip code, or city" text and line and text field <br>(including clickable white space) | RES2_EAZ | /need-help#Step2 |
| "Enter address, zip code, or city" text and line and text field <br>(including clickable white space) | OFS2_EAZ | /offer-help#Step2 |

Screen Shot 2020-10-12 at 5 25 28 PM

### 2. Help Board (url path: /feed)

**Issue:** `Enter address, zip code, or city` ID does not show up on GTM when clicked on.

| Component on page | JSX 'id' attribute |
| --- | --- |
| Enter address, zip code, or city" text and line and text field <br>(including clickable white space) | HB_LO_EAZ |

Screen Shot 2020-10-12 at 5 27 57 PM

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
for #1644: fixes GTM tag for locationInput, which is an antd Select input, turns out just giving the id to the parent element doesn't appear after render, so the id must be given to a specific child that's only accessible after render.
for #1643: fixes Localisation GTM ids
for #1642: fixes GTM tags for avatar upload, and email organization icon

_Please be concise and link any related issue(s):_
closes #1644
closes #1643
closes #1642

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by joshmorel** [comment]
Thanks @Zaydme . This is an area (GTM) I'm less familiar with so not quite sure about approving or requesting changes. The change to fix #1643 in particular, I'm not sure the cause of the issue and how this will change it.

How do we test these in review environment or do we need to merge to staging to test, @doheekim93 @tr1503 @idjevm ?

File: client/src/components/Header.js [hunk 1]
```diff
@@ -143,17 +143,18 @@ export default ({
   const languageMenu = (
     <Menu>
       {Object.entries(languages).map(([key, label]) => (
-        <Menu.Item id={GTM.nav.prefix + GTM.nav.language + GTM.language[key]} key={key}>
-          <a
+        <Menu.Item key={key}>
+          <span
```
Comment (joshmorel) [inline client/src/components/Header.js]: Okay I do see how this should solve it, moving the id to the same element as the event listener.

This would work except why change to `span`? The issue now is since it's `inline` you can't click on the menu item where there is no text.

no-click-menu

We should either:

a) change `span` to an block element - either back to `a` or `div`
b) Move `id` back to `Menu.Item` **along with** event listener

**Review by joshmorel — CHANGES_REQUESTED** [review]
Thanks @Zaydme . I think we can merge and test in staging once we resolve the 1 identified issue.

**Comment by idjevm** [comment]
:O Oh I am testing this locally, please don't mergeeeeee yet

File: client/src/components/Header.js (hunk 1 above)
Comment (joshmorel) [reply client/src/components/Header.js]: @Zaydme since the resolution was straight forward I went ahead. We'll merge to staging and then get the BI team to confirm all resolutions.

**Comment by joshmorel** [comment]
@idjevm can you please re-pull? I just added resolution to the one issue I identified for Menu.Item change.

**Comment by idjevm** [comment]
Doing! Thank you @joshmorel !

**Comment by ashminbhandari** [comment]
Looks good code-wise! Just don't know how to check if they are firing properly!

File: client/src/components/Header.js (hunk 1 above)
Comment (Zaydme) [reply client/src/components/Header.js]: @joshmorel 
a) After some testing I found out that GTM doesn't fire on `<a>` so had to change it to `<span>`
b) Moving id back to Menu.Item doesn't fire, because the click is being detected on the child `<span>`

Comment (Zaydme) [reply client/src/components/Header.js]: but there is no problem with moving the event listener

**Comment by joshmorel** [comment]
> Okay I do see how this should solve it, moving the id to the same element as the event listener.

This seems like it is not correct based on @idjevm testing of my change. Maybe it's something about the onClick callback used by antd - https://github.com/fis-components/rc-menu/blob/eda74d37bf41a21fe2bfa89eae7fbe04dff4548c/lib/MenuItem.js#L94. 

However I realize we need it also in mobile nav as the language menu is duplicated in stead of re-used.

**Comment by joshmorel** [comment]
Okay. So I think language menu should work. Can you test for both mobile and desktop @idjevm the menu is duplicated so I needed to fix mobile as well (I will create a "good first issue" to create a separate component).

**Comment by joshmorel** [comment]
However for location, @Zaydme,  the ID is duplicated here:

image

Not sure if it will cause issues, but it might?

Why add it to both

* `.ant-select-selection-item`: https://github.com/FightPandemics/FightPandemics/blob/b5c2cd9d52cecf582939eeeffe3bf3fd38d0401f/client/src/components/Input/LocationInput.js#L95
* & `SubLabel`: https://github.com/FightPandemics/FightPandemics/blob/b5c2cd9d52cecf582939eeeffe3bf3fd38d0401f/client/src/components/Input/LocationInput.js#L201

Should we remove from SubLabel or have a different ID? The SubLabel is not interactive but it is updated on address selection so maybe that's what was supposed to work at first (but isn't).

If you have an idea @idjevm for this one please share.

File: client/src/components/Header.js (hunk 1 above)
Comment (joshmorel) [reply client/src/components/Header.js]: Thanks @Zaydme . Wasn't sure if you'd be able to do this til late today so I gave it a shot. b didn't work. I changed it to `div` so hopefully that is fine (@idjevm will confirm). We could also change style on span to display: block but I would be suprised if `span` worked and `div` didn't...

**Comment by Zaydme** [comment]
@joshmorel please check this https://github.com/FightPandemics/FightPandemics/issues/1644
img
As you can see, the red box includes the `<small>`

**Comment by joshmorel** [comment]
@Zaydme 

> As you can see, the red box includes the `<small>`

I guess my question is why also add to the `span.ant-select-selection-item` then?

image

Might this result in duplicate triggering?

**Comment by Zaydme** [comment]
@joshmorel `span.ant-select-selection-item` is where the user clicks, so it's the main GTM id we really need, maybe we can remove it from the `<small>` and tell BI that only clicking on the input will trigger and not the sub text.

**Comment by doheekim93** [comment]
@joshmorel @Zaydme Yes, the GTM just needs to trigger on the click -- which means any whitespace/text/element that triggers an "event". In this case, I believe the cursor blinking to allow users to enter the location is triggered when they click on the whitespace and the blue line and _not_ on the "Enter address, zip code, or city" text (which means that my diagram was wrong -- sorry!)

**Comment by joshmorel** [comment]
> @joshmorel `span.ant-select-selection-item` is where the user clicks, so it's the main GTM id we really need, maybe we can remove it from the `<small>` and tell BI that only clicking on the input will trigger and not the sub text.

> @joshmorel @Zaydme Yes, the GTM just needs to trigger on the click -- which means any whitespace/text/element that triggers an "event". In this case, I believe the cursor blinking to allow users to enter the location is triggered when they click on the whitespace and the blue line and not on the "Enter address, zip code, or city" text (which means that my diagram was wrong -- sorry!)

Makes sense. In that case `span.ant-select-selection-item` seems to be what we want. Might not be harmful to leave on `<small>` but probably safest to remove it from there.

**Review by joshmorel — APPROVED** [review]
Great thanks @Zaydme 

@idjevm test locally w GTM and if all looks good please merge into staging.

**Review by idjevm — APPROVED** [review]
LGTM! I tested them locally and they all seem to fire! @doheekim93 I will go ahead and merge this, please feel free to reopen if the issue persits! 

Thank you so much @Zaydme & @joshmorel !!

**Comment by doheekim93** [comment]
Just checked on GTM and it looks good to me!! Will still need the BI team to check again (make sure I didn't miss anything), but I think we should be good to go!

Thank you @Zaydme @joshmorel @idjevm !!!
