### PR TITLE
fix post patch undefined postProps

### LINKED ISSUE #653: `postProps` undefined in `PATCH /api/posts/:postId`
Seems like I've spotted a bug here

https://github.com/FightPandemics/FightPandemics/blob/master/backend/lib/endpoints/posts.js#L348

```
      if (EXPIRATION_OPTIONS.includes(postProps.expireAt)) {
        body.expireAt = moment().add(1, `${body.expireAt}s`);
```

And makes me wonder why this got merged, should probably be caught by ESLint and preventing to commit...

### PR DESCRIPTION
**Pull request by joshmorel**
### What does this pull request aim to achieve? 💯

Resolves #653 

@robinv85  on your comment

> And makes me wonder why this got merged, should probably be caught by ESLint and preventing to commit...

husky will prevent this but **only** if installed and I think it can be skipped to. We could add to github actions workflows but right now that will create a lot more headaches than it is worth - we can look into this again post MVP. (Create a ticket?)

### 🚨Before submitting this pull request🚨:

_Please do **NOT** submit this PR if you have not done the following:_

1. I have checked that no one else is working on similar changes.
2. I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
3. The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
4. This branch is rebased/merged with the **latest master**.
5. There are no merge conflicts.
6. There are no console warnings and errors.
7. On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

File: backend/lib/endpoints/posts.js [hunk 1]
```diff
@@ -332,7 +332,7 @@ async function routes(app) {
       schema: updatePostSchema,
     },
     async (req) => {
-      const { userId } = req;
+      const { userId, body: postProps } = req;
```
Comment (robinv85) [inline backend/lib/endpoints/posts.js:335]: one line is probably not sufficient
in the code below there's also 
`const { body } = req;`
and then both `postProps` and `body` are used so should be one const

Comment (joshmorel) [reply backend/lib/endpoints/posts.js]: Silly me just fixing error without looking at rest of code. :sweat_smile: 

The `{ body: postProps }` thing is only used in POST post. Other places use `{ body } = req` or just `req.body` so we're not exactly consistent. I think `{ body } = req` is good, you?
