### PR TITLE
changed 'organization' to 'organisation' everywhere

### LINKED ISSUE #1035: Feed - When adding a post the box "Organization' is spelled "Organisation" with s. *** We need to update with S everywhere on Mobile****
When adding a post on Feed, the box "Organization' is spelled "Organisation" with s.

Steps to Reproduce:

Pre-Requisite: Be signed in

1 - Click on the 3 lines on the top right of the page
2 - Click on Feed
3 - Click on Plus icon

Current Result: Organisation 
Expected: Organization (as per Figma)

image

### PR DESCRIPTION
**Pull request by BMariscal**
Closes #1035

### CODE REVIEW

File: client/src/hooks/reducers/organisationReducers.js [hunk 1]
```diff
@@ -1,26 +1,26 @@
...
-  FETCH_ORGANIZATION,
-  FETCH_ORGANIZATION_ERROR,
-  FETCH_ORGANIZATION_SUCCESS,
-  UPDATE_ORGANIZATION,
-  UPDATE_ORGANIZATION_ERROR,
-  UPDATE_ORGANIZATION_SUCCESS,
-} from "../actions/organizationActions";
+  CREATE_Organisation,
+  CREATE_Organisation_ERROR,
+  //CREATE_Organisation_SUCCESS,
```
Comment (nr431207) [inline client/src/hooks/reducers/organisationReducers.js:4]: this could be removed since not being used

Comment (BMariscal) [reply client/src/hooks/reducers/organisationReducers.js:4]: ooh nice catch! thanks Sonia!

**Comment by idjevm** [comment]
It also means that now we have a `organizations` mongodb document that is stale, and we should either remove it or move it to `organisations`
