### PR TITLE
Fixed word-wrap in mobile web

### LINKED ISSUE #928: Post description goes  beyond the Post detail page
Post description goes beyond the Post detail page as shown in picture 2. 
Steps: login staging FP and go  to feed,create Post as Individual/Organization. Enter the description until the entire row is filled.Create Post and view post.

image

Picture 2
image

### LINKED ISSUE #952: Fix post width dimensions
env: [https://staging.fightpandemics.work/feed](url)

When user is on a single post's page (i.e. click on a post from feed or under My Activity - [example](https://staging.fightpandemics.work/post/5ef8e463ebf82400121b1d29), the post width size should be fixed. It should not be dynamically changing depending on the contents (length of text) of the post.

ezgif com-video-to-gif (2)

### PR DESCRIPTION
**Pull request by BMariscal**
Closes #928
Closes #952

You should no longer see div overflow in mobile AND post width should not expand based on content for both web and mobile web.

### CODE REVIEW

File: client/src/components/Feed/Post.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ import WizardFormNav, {
   StyledButtonWizard,
 } from "components/StepWizard/WizardFormNav";
 import { StyledLoadMoreButton } from "./StyledCommentButton";
+import {StyledPostPagePostCard} from "./StyledPostPage";
```
Comment (idjevm) [inline client/src/components/Feed/Post.js:22]: Check your eslint config, there should be spaces here.

File: client/src/components/Feed/StyledPostPage.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+  width: 50%;
+  @media screen and (max-width: ${mq.phone.wide.maxWidth}) {
+    width: 100%;
+    position: relative;
+    overflow-wrap: break-word;
+  }      
+`;
+
+export const StyledPostPagePostCard = styled(PostCard)`
+  max-width: 80rem;
```
Comment (idjevm) [inline client/src/components/Feed/StyledPostPage.js:15]: The only issue I see with this one is if it is a 4k Resolution then it will be tooo small.
