### PR TITLE
Fix feed GTM tags

### LINKED ISSUE #1147: GTM ID's not showing up
**How to set up GTM debugging on Local: [https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255](https://www.notion.so/fightpandemics/GTM-Debugging-on-Local-68eba58926a445cc9e2447843bdef255)

The following IDs have already been assigned to the correct components. Issue is that GTM does **not** pick up on these IDs.

### 1. Filter Categories (url path: /feed)

**Issue:** `Location`, `Providers`, and `Type` IDs do not show up on GTM when clicked on.

| Element on page | JSX 'id' attribute |
| --- | --- |
| "Location" text and + Button <br>(including clickable white space) | HB_LO |
| "Providers" text and + Button <br>(including clickable white space) | HB_PV |
| "Type" text and + Button <br>(including clickable white space) | HB_TP |

Screen Shot 2020-07-13 at 5 03 41 PM

### 2. View More button (url path: /feed)

**Issue:** `View More` IDs do not show up on GTM when clicked on.

| Element on page | JSX 'id' attribute |
| --- | --- |
| "View More" text | HB_VM_postnumber |

Screen Shot 2020-07-13 at 6 00 23 PM

### 3. Create a Post (on help board page, on individual profile page, and on organisation profile page)

**Issue:** GTM does **not** show the assigned IDs when clicking on the **red** shaded areas (text and icon), but it _does_ show the IDs when clicking on the green shaded areas.

| Element on page | JSX 'id' attribute |
| --- | --- |
| Individual Button | HB_CP1_IN |
| Organisation Button | HB_CP1_ORG |

Screen Shot 2020-07-13 at 5 04 33 PM

### 4. url path: /offer-help

**Issue:** GTM does **not** show the assigned IDs when clicking on the **red** shaded areas (text), but it _does_ show the IDs when clicking on the green shaded areas.

| Element on page | JSX 'id' attribute |
| --- | --- |
| "As a Volunteer" Button | OFS1_VO |
| "As a Donor/Investor" Button | OFS1_DI |
| "As an organisation" Button | OFS1_ORG |

Screen Shot 2020-07-13 at 5 41 10 PM

### 5. Post page: View Less button

**Issue:** The `View Less` button on posts has the same ID as the `View More` button. The `View Less` button does **not** need an ID assigned to it.

Screen Shot 2020-07-13 at 6 00 36 PM

### 6. LinkedIn ID change to _LN
sign in page: /auth/login
Change Linkedin ID to: SI_LN

sign up page: /auth/signup
Change LinkedIn ID to: SU_LN

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯
Fixes feed GTM tags

_Please be concise and link any related issue(s):_
closes #1147

### CODE REVIEW

File: client/src/components/StepWizard/WizardCheckboxItem.js [hunk 1]
```diff
@@ -73,7 +75,7 @@ export const WizardCheckboxItem = ({ text, checked, onChange, ...props }) => {
       {...props}
     >
       <StyledCheckbox checked={checked} />
-      <span className="text">{text}</span>
+      <StyledSpan className="text">{text}</StyledSpan>
```
Comment (idjevm) [inline client/src/components/StepWizard/WizardCheckboxItem.js]: We can probably remove the `className="text"` here, I don't think it is being used anywhere.

**Comment by idjevm** [comment]
Almost there, but I think this should be left aligned ? rather than centered? 
Before: 
image

Now:
image

**Comment by jyclam** [comment]
Fixed! Thanks for catching that.
