### PR TITLE
Fix various GTM bugs

### LINKED ISSUE #1081: GTM ID Fixes
Please include all elements in component!

### url path: /need-help
| Element on page | JSX 'id' attribute |
| --- | --- |
| Medical Help Button | RES1_MH |
| Other Help Button | RES1_OH |

### url path: /need-help#Step2
| Element on page | JSX 'id' attribute |
| --- | --- |
| "Share My Location" Button (including icon <br>and the entire clickable whitespace area) | RES2_SL |

### url path: /need-help#Step3
| Element on page | JSX 'id' attribute |
| --- | --- |
| Skip Button (the entire clickable area) | RES3_SK |

### For all post's page w/ url path: /post/XXXXX
| Element on page | JSX 'id' attribute |
| --- | --- |
| Share icon + "Share" text | PO_SH_postnumber |

### url path: /offer-help#Step1
The element IDs should be OFS1_ not OFS_

### url path: /offer-help#Step2
| Element on page | JSX 'id' attribute |
| --- | --- |
| "Share My Location" Button (including icon <br>and the entire clickable whitespace area) | OFS2_SL |

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯
Fix various GTM bugs persisting after PR #1091

closes #1081

### CODE REVIEW

**Comment by jyclam** [comment]
This is ready for review. Addresses currently known GTM bugs. 

I'm getting a testing dedicated GTM container setup to test current and future GTM work against. But given soft launch code freeze deadline, we should probably go low tech and just merge and test on production for now.

File: client/src/components/Input/Checkbox.js [hunk 1]
```diff
@@ -5,6 +5,8 @@ import { theme } from "constants/theme";
 const { darkGray } = theme.colors;
 
 const StyledCheckbox = styled(Checkbox)`
+  pointer-events: none !important;
+
```
Comment (omarzoghayyer) [inline client/src/components/Input/Checkbox.js:9]: extra space
