### PR TITLE
Create organization error handling fixes

### LINKED ISSUE #868: Unable to ADD new Organization (Show message that email is not unique)
1. Open"https://staging.fightpandemics.work"
2. Login with valid email/password
3. Navigate Profile ->Add Organization
4. Enter all the details in 'Add Organization' page and click on 'Create Profile' button

Issue# You will observe nothing will happen, user stay on same page, no message or error is displayed.
P.S. attached GIF.

https://share.getcloudapp.com/X6uo8eKy

### PR DESCRIPTION
**Pull request by kylejvh**
Closes #868.

Adds the same user-friendly frontend error handling for user sign up to organization creation. Implements changes to backend organization post route to support specific error messages.

org error handling

### CODE REVIEW

**Comment by joshmorel** [comment]
I added this ticket to iterate on this - #981 

But @kylejvh  this is good for now once you resolve @idjevm issue.

File: client/src/pages/CreateOrganizationProfile.js [hunk 1]
```diff
@@ -138,8 +143,10 @@ const CreateOrgProfile = (props) => {
           });
         }
       } else {
-        alert("You must be logged in to create an organization profile");
-        return;
+        return createOrganizationFormDispatch({
+          type: CREATE_ORGANIZATION_ERROR,
+          error: `You must be logged in to create an organization profile`,
+        });
```
Comment (idjevm) [inline client/src/pages/CreateOrganizationProfile.js:149]: I find this unnecessary though, as the user will not be able to even get to the point of trying to create an org profile without proper authentication nor having an user profile.

File: client/src/pages/CreateOrganizationProfile.js [hunk 2]
```diff
@@ -105,11 +106,15 @@ const CreateOrgProfile = (props) => {
...
+        type: CREATE_ORGANIZATION_ERROR,
+        error: `You must agree to our privacy policy before proceeding`,
+      });
     } else if (!conditions) {
-      alert("You must agree to our terms and conditions before proceeding");
-      return;
+      return createOrganizationFormDispatch({
+        type: CREATE_ORGANIZATION_ERROR,
+        error: `You must agree to our terms and conditions before proceeding`,
+      });
```
Comment (idjevm) [inline client/src/pages/CreateOrganizationProfile.js:117]: These two could also be unnecessary or we should change a bit of the logic on the `Create Profile` button, thing is that the way that right now it is happening is that the button will not be enabled until the user checks both boxes. I think this approach of showing the error is better, so perhaps let's work around that?

Comment (idjevm) [reply client/src/pages/CreateOrganizationProfile.js:117]: Also, check the Build URL, I am still getting this -> 
image

Comment (idjevm) [reply client/src/pages/CreateOrganizationProfile.js:117]: And this is because I am using the same email of the user / another org as well. I mean it is much better than it was / before we didn't even see anything , just the `create profile` button didn't do anything (looked like)

**Comment by rabbi08** [comment]
URL: https://featureshow-non-unique-org-email.fightpandemics.xyz/create-organization-profile

I am still seeing the "interns; server error"

Are we  planning to keep "server error" message or update "Duplicate Email" message?

image

File: client/src/pages/CreateOrganizationProfile.js (hunk 1 above)
Comment (idjevm) [reply client/src/pages/CreateOrganizationProfile.js:149]: Let's clean up later
